openapi: 3.0.3

info:
  version: 0.0.1
  title: Ecomm Orders API
  description: |-
    ## Orders Management

    CRUD operations within the database.
tags:

  - name: orders
    description: Orders usage
  - name: admin/orders
    description: Admin access to orders
paths:
  /api/admin/ordes/:
    post:
      tags:
        - admin/orders
      summary: Create new order
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        403:
          $ref: "#/components/responses/403"

  /api/orders/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      tags:
        - orders
      summary: List order by ID
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"

components:
  schemas:
    Order:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          userId:
            type: string
          deliveryAddres:
            type: object
            properties:
              street:
                type: string
              number:
                type: string
              complement:
                type: string
              zipCode:
                type: string
              city:
                type: string
              state:
                type: string
          items:
            type: array
            items:
              type: object
              properties:
                productId:
                  type: string
                amount:
                  type: number
                discount:
                  type: number
                unitPrice:
                  type: number

  responses:
    200:
      description: Success
      content:
        application/json:
          example: "Success"
    201:
      description: Accepted
      content:
        application/json:
          example: "Accepted"
    204:
      description: No content
      content:
        application/json:
          example: "No content"    
    404:
      description: Not found
      content:
        application/json:
          example: "Not Found"
    403:
      description: Forbiden
      content:
        application/json:
          example: "Access denied"