version: "3.9"
services:
  product-container:
    build: ./product/
    volumes:
      - ./product/:/app/product
    ports:
      - 8001:8001
  account-container:
    build: ./account/
    volumes:
      - ./account/:/app/account
    ports:
      - 8002:8002
  mongo-ecomm:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
  mysql-ecomm:
    image: mysql
    restart: always
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
