version: "3.9"
services:

  mysql:
    image: mysql
    container_name: mysql-ecomm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3333:3333
  mongodb:
    image: mongo
    container_name: mongo-ecomm
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
  product-container:
    container_name: ecomm-product
    build: ./product/
    volumes:
      - ./product/:/app/product
    ports:
      - 8001:8001
    depends_on:
      - mongodb
  account-container:
    container_name: ecomm-account
    build: ./account/
    volumes:
      - ./account/:/app/account
    ports:
      - 8002:8002
    depends_on:
      - mongodb
  finance-container:
    container_name: ecomm-finance
    build: ./finance/
    restart: always
    volumes:
      - ./finance/:/app/finance
    ports:
      - 3306:3306
    depends_on:
      - mysql

  api-gateway:
    build: ./gateway
    container_name: ecomm-api-gateway
    volumes:
      - ./gateway:/app/ecomm-api-gateway
    ports:
      - 3000:3000
    depends_on:
      - account-container
      - finance-container
      - product-container
volumes:
  db-mongo-ecomm:
  db-mysql-ecomm: