openapi: 3.0.3

info:
  version: 0.0.1
  title: Ecomm Products API
  description: |- 
    ## Products Storage Management
    
    CRUD operations within the database.
servers:
  - url: https://63cfde3a109824043787c8de.mockapi.io/
    description: MockAPI
tags:
  - name: default
    description: Categories
  - name: admin
    description: Admin Access

paths:
  /api/categories:
    get:
      summary: List all categories
      responses: 
        200:
          description: Success
          headers:
            id:
              schema: 
                type: string
            name:
              schema:
                type: string
            status:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    status:
                      type: string                      
        404:
          description: Categories not found
          content: 
            application/json:
              example: "Not Found"

  /api/admin/categories:
    post:
      tags:
        - admin
      summary: Create new category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                status: 
                  type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    status:
                      type: string                      
        403: 
          description: Forbiden
          content:
            application/json:
              example: "Access denied"

  /api/categories/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      tags:
        - default
      summary: List category by ID
      responses:
        200:
          description: Success
          headers:
            id:
              schema: 
                type: string
            name:
              schema:
                type: string
            status:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    status:
                      type: string
        404:
          description: ID not found
          content: 
            application/json:
              example: "Not Found"