openapi: 3.0.3

info:
  version: 0.0.1
  title: Ecomm Products API
  description: |- 
    ## Products Storage Management
    
    CRUD operations within the database.
# servers:

tags:
  - name: categories
    description: Categories usage
  - name: admin/categories
    description: Admin access to categories

paths:
  /api/categories:
    get:
      tags:
        - categories
      summary: List all categories
      responses: 
        200:
          description: Success
          headers:
            id:
              schema: 
                type: string
            name:
              schema:
                type: string
            status:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    status:
                      type: string                      
        404:
          description: Categories not found
          content: 
            application/json:
              example: "Not Found"

  /api/admin/categories:
    post:
      tags:
        - admin/categories
      summary: Create new category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                status: 
                  type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    status:
                      type: string                      
        403: 
          description: Forbiden
          content:
            application/json:
              example: "Access denied"

  /api/categories/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      tags:
        - categories
      summary: List category by ID
      responses:
        200:
          description: Success
          headers:
            id:
              schema: 
                type: string
            name:
              schema:
                type: string
            status:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    status:
                      type: string
        404:
          description: ID not found
          content: 
            application/json:
              example: "Not Found"

  /api/admin/categories/{id}:
    parameters:
      - name: id
        in: path
        schema:
         type: string
        required: true
    put:
      tags:
        - admin/categories
      summary: Update category data by ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                status: 
                  type: string
      responses:
        200:
          description: Category Updated
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    status:
                      type: string
        404:
          description: ID not found
          content: 
            application/json:
              example: "ID Not Found"
              
    delete:
      tags:
        - admin/categories
      summary: Delete category by ID
      responses:
        200:
          description: Success
          content:
            application/json:
              example: "Category deleted"

    patch:
      tags:
        - admin/categories
      summary: Update category status by ID
      responses:
        204:
          description: Success
          content:
            application/json:
              example: "Status Updated"
        404:
          description: ID not found
          content: 
            application/json:
              example: "ID Not Found"                     